# Generated by Django 3.2 on 2021-05-02 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='کد')),
            ],
            options={
                'verbose_name': 'اطلاعات پایه',
                'verbose_name_plural': 'اطلاعات پایه ها',
            },
        ),
        migrations.CreateModel(
            name='BaseInformationHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('code', models.IntegerField(blank=True, null=True, unique=True, verbose_name='کد')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سرفصل اطلاعات پایه',
                'verbose_name_plural': 'سرفصل های اطلاعات پایه',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='عنوان منطقه')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_information_setting.zone', verbose_name='والد')),
                ('ztype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_information_setting.baseinformation', verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'تقسیمات جغرافیایی',
                'verbose_name_plural': 'تقسیمات جغرافیایی ها',
            },
        ),
        migrations.AddField(
            model_name='baseinformation',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_information_setting.baseinformationheader', verbose_name='سرفصل'),
        ),
        migrations.AddField(
            model_name='baseinformation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_information_setting.baseinformation', verbose_name='والد'),
        ),
    ]
