# Generated by Django 3.2 on 2021-05-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210506_1729'),
        ('base_information_setting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Privacy',
        ),
    ]
