# Generated by Django 3.2 on 2021-05-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_information_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baseinformation',
            unique_together={('code', 'header')},
        ),
    ]
