# Generated by Django 3.2 on 2021-05-07 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrelation',
            name='a_user',
        ),
        migrations.RemoveField(
            model_name='userrelation',
            name='b_user',
        ),
        migrations.AddField(
            model_name='educationhistory',
            name='place_number_for_sorting',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره مرتب سازی'),
        ),
        migrations.AddField(
            model_name='effect',
            name='place_number_for_sorting',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره مرتب سازی'),
        ),
        migrations.AddField(
            model_name='standpoint',
            name='place_number_for_sorting',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره مرتب سازی'),
        ),
        migrations.AddField(
            model_name='userrelation',
            name='base_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='u_ur_base_user', to='users.user', verbose_name='نامزد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrelation',
            name='base_user_verification',
            field=models.BooleanField(blank=True, null=True, verbose_name='تایید رابطه توسط کاربر پایه'),
        ),
        migrations.AddField(
            model_name='userrelation',
            name='related_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='u_ur_related_user', to='users.user', verbose_name='کاربر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrelation',
            name='related_user_verification',
            field=models.BooleanField(blank=True, null=True, verbose_name='تایید رابطه توسط کاربر مرتبط'),
        ),
        migrations.AddField(
            model_name='workexpiration',
            name='place_number_for_sorting',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره مرتب سازی'),
        ),
        migrations.AlterUniqueTogether(
            name='educationhistory',
            unique_together={('place_number_for_sorting', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='effect',
            unique_together={('place_number_for_sorting', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='standpoint',
            unique_together={('place_number_for_sorting', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='workexpiration',
            unique_together={('place_number_for_sorting', 'user')},
        ),
        migrations.CreateModel(
            name='VCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(editable=False, max_length=5, verbose_name='کد')),
                ('_vctype', models.CharField(choices=[('0', 'شماره تلفن'), ('1', 'ایمیل')], max_length=2, verbose_name='نوع')),
                ('expiration_date', models.DateTimeField(editable=False, verbose_name='تاریخ انقضا')),
                ('used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('valid', models.BooleanField(default=False, verbose_name='قابل قبول')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
