# Generated by Django 3.2 on 2021-05-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='json_t',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
