# Generated by Django 3.2 on 2021-05-04 12:37

from django.db import migrations, models
import repository.regular_expression


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_email_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, validators=[repository.regular_expression.UnicodePasswordValidator], verbose_name='کلمه عبور'),
        ),
    ]
