# Generated by Django 3.2 on 2021-05-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210507_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vcode',
            options={'verbose_name': 'کد تایید', 'verbose_name_plural': 'کدهای تایید'},
        ),
        migrations.RemoveField(
            model_name='vcode',
            name='valid',
        ),
        migrations.AlterField(
            model_name='vcode',
            name='_vctype',
            field=models.CharField(choices=[('0', 'شماره تلفن'), ('1', 'ایمیل')], editable=False, max_length=2, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='vcode',
            name='used',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='استفاده شده'),
        ),
    ]
