# Generated by Django 3.2 on 2021-05-07 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_information_settings', '0001_initial'),
        ('users', '0003_auto_20210507_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='standpoint',
            name='group',
            field=models.ForeignKey(default=1, help_text='این دیدگاه مربوط به کدام دسته بندی -مثلا دسته بندی سیاست خارجی، امور اجتماعی و ...-است.', on_delete=django.db.models.deletion.CASCADE, to='base_information_settings.baseinformation', verbose_name='دسته بندی'),
            preserve_default=False,
        ),
    ]
