# Generated by Django 3.2 on 2021-05-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210502_0613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkExperition',
            new_name='WorkExpiration',
        ),
    ]
