# Generated by Django 3.2 on 2021-05-04 13:41

from django.db import migrations, models
import repository.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=repository.uploader.image_upload_to, verbose_name='عکس پروفایل'),
        ),
    ]
