# Generated by Django 3.2 on 2021-05-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_information_settings', '0001_initial'),
        ('users', '0004_standpoint_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='etype',
            field=models.ForeignKey(default=1, help_text='این اثر از چه نوعی - کتاب، مقاله، فیلم و ...- است.', on_delete=django.db.models.deletion.CASCADE, to='base_information_settings.baseinformation', verbose_name='نوغ'),
            preserve_default=False,
        ),
    ]
