# Generated by Django 3.2 on 2021-05-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_effect_etype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrelation',
            name='_is_verify',
            field=models.BooleanField(default=False, verbose_name='تایید رابطه'),
        ),
    ]
