# Generated by Django 3.2 on 2021-05-12 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_information_settings', '0001_initial'),
        ('users', '0006_userrelation__is_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_information_settings.baseinformation', verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش ها',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date_time', models.DateTimeField(verbose_name='از')),
                ('to_date_time', models.DateTimeField(verbose_name='تا')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role', verbose_name='نقش')),
            ],
            options={
                'verbose_name': 'نقش کاربر',
                'verbose_name_plural': 'نقش های کاربران',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='privacy',
        ),
        migrations.AlterUniqueTogether(
            name='userrelation',
            unique_together={('base_user', 'related_user')},
        ),
        migrations.DeleteModel(
            name='Privacy',
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
