# Generated by Django 3.2 on 2021-05-12 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_information_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='عنوان')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('file', models.FilePathField(blank=True, null=True, verbose_name='فایل')),
                ('send', models.BooleanField(default=False, verbose_name='ارسال شد')),
                ('received', models.BooleanField(default=False, verbose_name='دریافت شد')),
                ('read', models.BooleanField(default=False, verbose_name='خوانده شد')),
                ('pending', models.BooleanField(default=False, verbose_name='در حال بررسی')),
                ('checked_out', models.BooleanField(default=False, verbose_name='بررسی شد')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده')),
                ('t_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_information_settings.baseinformation', verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='عنوان')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('file', models.FilePathField(blank=True, null=True, verbose_name='فایل')),
                ('send', models.BooleanField(default=False, verbose_name='ارسال شد')),
                ('received', models.BooleanField(default=False, verbose_name='دریافت شد')),
                ('read', models.BooleanField(default=False, verbose_name='خوانده شد')),
                ('t_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_information_settings.baseinformation', verbose_name='نوع')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing.ticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ ها',
            },
        ),
    ]
