# Generated by Django 3.2 on 2021-05-06 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_information_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_is_suspension', models.BooleanField(default=False, verbose_name='تعلیق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کاندید',
                'verbose_name_plural': 'کاندیدها',
            },
        ),
        migrations.CreateModel(
            name='CandidateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'ائتلاف',
                'verbose_name_plural': 'ائتلافات',
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_year', models.IntegerField(verbose_name='از سال')),
                ('to_year', models.IntegerField(verbose_name='تا سال')),
                ('period', models.IntegerField(verbose_name='دوره')),
                ('date', models.DateField(verbose_name='تاریخ برگزاری')),
                ('duration_of_the_event', models.DateField(blank=True, null=True, verbose_name='مدت زمان برگزاری')),
                ('round', models.IntegerField(default=1, verbose_name='دور')),
                ('etype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_information_setting.baseinformation', verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'انتخابات',
                'verbose_name_plural': 'انتخابات ها',
            },
        ),
        migrations.CreateModel(
            name='RegisterCandidatePerElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='تاریخ ثبت نام')),
                ('slogan', models.CharField(blank=True, max_length=256, null=True, verbose_name='شعار')),
                ('candidate_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان نامزد')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.candidate', verbose_name='نامزد')),
                ('candidate_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.candidategroup', verbose_name='ائتلاف')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.election', verbose_name='انتخابات')),
            ],
            options={
                'verbose_name': 'نماینده شرکت کننده در انتخابات',
                'verbose_name_plural': 'نمایندگان شرکت کننده در انتخابات ها',
            },
        ),
    ]
