# Generated by Django 3.2 on 2021-04-19 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationalcode',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[users.models.UnicodeNationalcodeValidator()], verbose_name='شماره ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[users.models.UnicodePhonenumberValidator()], verbose_name='شماره تلفن'),
        ),
        migrations.CreateModel(
            name='WorkExperition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=128, verbose_name='عنوان جایگاه')),
                ('cooperation_type', models.CharField(blank=True, choices=[('1', 'پاره وقت'), ('2', 'تمام وقت'), ('3', 'مشاوره')], max_length=10, null=True, verbose_name='نوع همکاری')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='از تاریخ')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='تا تاریخ')),
                ('activity_type', models.CharField(blank=True, choices=[('1', 'قراردادی'), ('2', 'پیمانی'), ('3', 'رسمی')], max_length=10, null=True, verbose_name='نوع فعالیت')),
                ('organization_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام سازمان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سابقه کاری',
                'verbose_name_plural': 'سوابق کاری',
            },
        ),
    ]
